services:
  store2024:
    image: aaronbee2010/store2024:latest
    environment:
        ACCOUNT_SERVICE_API_BASE: http://172.19.10.101:5173
        INVENTORY_SERVICE_API_BASE: http://172.19.10.102:5180
        SHOPPING_SERVICE_API_BASE: http://172.19.10.103:5219
        
    build:
      context: ./Store2024
      dockerfile: Dockerfile
    ports:
      - "5146:5146"
    networks:
      store2024network:
        ipv4_address: 172.19.10.100

  accountservice:
    image: aaronbee2010/accountservice:latest
    build:
      context: ./Services/AccountService
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      store2024network:
        ipv4_address: 172.19.10.101

  inventoryservice:
    image: aaronbee2010/inventoryservice:latest
    build:
      context: ./Services/InventoryService
      dockerfile: Dockerfile
    ports:
      - "5180:5180"
    networks:
      store2024network:
        ipv4_address: 172.19.10.102

  shoppingservice:
    image: aaronbee2010/shoppingservice:latest
    build:
      context: ./Services/ShoppingService/
      dockerfile: Dockerfile
    ports:
      - "5219:5219"
    networks:
      store2024network:
        ipv4_address: 172.19.10.103

networks:
  store2024network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/16
